language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
- '8'
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - secure: aJiOXPRWn+X+vgdhHtk82D8khtlruWt7DA3qCT1QiNM0JJrmqLDuXZV5wbskjrgwpLVo1vcsSV44qePVd74wh4sSKDv/+0FGeVyBujOCFV3meG9leIdCRi1Rj2lGQXq8kKRfD3MX2YFx0Th2Ge8l6wpJrStDzn5EOBDmS8OAbmSQ0YVOEWseEa1/w9OJKGD8tiQWz8/VDZ1xLPtqKxfQQyv+NLlvecHMlRn1zDkVQz/keUdj9+EeHXKhxyRwcdFwmTjw/39bNmAgF0A+wjR5egAAJ2To2IWoh9UwqBdhUdFQGQbjJ4PvHPvGsCujLJE1s4dBjEOEQV2MCOCRN61OWqZyIIvgRX7LyZPx4PkQZ1q8zVmygX/c3Bw6KUXunKvXt5ioWL7snAKgzl41Nyl7eBtyRUjg/3k5OPdsrDrbl2vx8Aew5vMQbC0G0iQhTRw9OZUItDHwX9D/bpWHn3ko+6ix9pseIS3iJ+7Met/NMTWBVmJS2NBnjfWtkXaBMRzuI1+jfxo3GzC1B2+ojgyxYgC02NxuAvsDt9hDyFthEXUJskJldagvSTcPAJmqYhGE7NzjnrmxTitL5MGVf73lzbp6WzzrHDZ8GOaS79V/dVtPFN6NqhZTkIaQ8+X9VaSeTkmtG76NQDX9ARcCxgA35PAdDNtrDAIkhCgbnqUvFyg=
