language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
- '8'
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - secure: qKKNjvq7UKeVajk5g1nOh/KkYjfLEAVP91UPAmPYuj1zTVhE0Zh3yDfl/9PFJ46G8ICABrygricax6l2MjPdxWhqaxcymjfa2woLjjrqMeWscqnCASc7NJCgMIXkKDXxxClRsLGa8M5t6dqDtozm0+32gtsPLO1NIbE3tiXY+fSeDMsAptz/FWErk+sO+1U5xtnRO41SqcKRi+JkmS/4UycZZrLBTDv03RaHo9WGJ6m6ZsSg2iIEgcDrqv/Wai+DT4KAmIo/jwVFlMca8jdMrDk9UKoXDCiK/PDUQNfEzAbVPsQNoHitRIVibrZIHjjYyG0OXurfMrJJLK1p0dvGvTcYMhYi0y450MXgD0+VqkWpwyH107OUhqrD3Ivc1OyvtMoSnR3XpcVAFxE1Zg/BTFcdcsdQnzAz8TIfShYcIg0upo67fN+89Mh3ftgumhRKq/tkY+XaDxQ3K6CtY2hxLZmVCCOIlx6GVVM4QTPcieevzcHN7g2XHAivWfL5tVPRan8zo7Hf7KEbmCjjXhS4rLW1qfyHN3Fv0A6yAzPg3A8mLpBQu220ZmOZiB+grDZd10YE+nkGT4HYRJIUtYfNESnFAezVMUJ7mziRVWvLqnmQMrhwaTC6oZMep6twVuk7eZSudHWPX/NeFhgggJ/oL8XEIisUWPWEIFFCJSX8xvg=
    - secure: sRWdRdywsgL30h+TH7VVztK0skbRV4bP+scHP2o2V596JFr2QrIQ/u+mHJAYW/t7Uh9MWtw7Ju6m+6MfIy7LN1qWuv/OcB1VGWP4XkZhmKFul8Wm7cSXMzXX05QnnC86V//9Jxcsbq5rXDZgKQt2dyH1ACYQz5du4cZ/0osgDXwMjUVBFrjGJJDXXfRGKluquLi7HdzownzL+RUo2t5yM+rEVc6NhYpNvsdpIjHdduCg10otjcfmCZAfJ+LZL5hnSc3/3gFIWGtiL8I9F1D8MWa2figwqMCaDD5ouT5d6n7sNfFCR3JlPPMl6gxU3b+3pPyInRVRrj/3Ltnx1qgJZ8uX0AdLQhpcHmNx3gGZwfbRF6sYtc5V8vEHHB3Xfj961lVETCBpqYpIoe5dBbIx8V8iZHSh7e6wr1IYo+/OVUzrJC70VxVcxZge4puXqnAeC6UmOsuKFl5W+Hi70h9rDsCGLvxPTFzISepJgdmS5hC9mROSmWG8Fjv/vPIKUxn37/KrnHswt+OW225odq9NwP9qwtjkXgPF02N2zuFOuTmutblw+ls9FdkvDM+Dys7iH5VunNRnWjgQzvJJhlzuEDbyUI4BQ5YydNUCCvGVXpaHhW90F+hVUv3IfRQbP0n5XJ6IdXG4W9H2HAsBMSGLQ+YWDCsm5M1cDit//Fd/SLI=
    - secure: aJiOXPRWn+X+vgdhHtk82D8khtlruWt7DA3qCT1QiNM0JJrmqLDuXZV5wbskjrgwpLVo1vcsSV44qePVd74wh4sSKDv/+0FGeVyBujOCFV3meG9leIdCRi1Rj2lGQXq8kKRfD3MX2YFx0Th2Ge8l6wpJrStDzn5EOBDmS8OAbmSQ0YVOEWseEa1/w9OJKGD8tiQWz8/VDZ1xLPtqKxfQQyv+NLlvecHMlRn1zDkVQz/keUdj9+EeHXKhxyRwcdFwmTjw/39bNmAgF0A+wjR5egAAJ2To2IWoh9UwqBdhUdFQGQbjJ4PvHPvGsCujLJE1s4dBjEOEQV2MCOCRN61OWqZyIIvgRX7LyZPx4PkQZ1q8zVmygX/c3Bw6KUXunKvXt5ioWL7snAKgzl41Nyl7eBtyRUjg/3k5OPdsrDrbl2vx8Aew5vMQbC0G0iQhTRw9OZUItDHwX9D/bpWHn3ko+6ix9pseIS3iJ+7Met/NMTWBVmJS2NBnjfWtkXaBMRzuI1+jfxo3GzC1B2+ojgyxYgC02NxuAvsDt9hDyFthEXUJskJldagvSTcPAJmqYhGE7NzjnrmxTitL5MGVf73lzbp6WzzrHDZ8GOaS79V/dVtPFN6NqhZTkIaQ8+X9VaSeTkmtG76NQDX9ARcCxgA35PAdDNtrDAIkhCgbnqUvFyg=
